version: "3.7"

services:
  api-postgres:
    image: "library/postgres:15.1-alpine"
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=quarkus
      - POSTGRES_PASSWORD=MyPassword
    networks:
      - apint

  api-redis:
    image: "library/redis:7.0.7-alpine"
    command: redis-server --requirepass apiredispass
    container_name: redis-cache
    environment:
      - REDIS_PASSWORD=apiredispass
    ports:
      - "6379:6379"
    networks:
      - apint

#  api-service:
#    build:
#      context: .
#      dockerfile: src/main/docker/Dockerfile.jvm
#    container_name: services-java-api
#    environment:
#      - POSTGRES_DB=mydatabase
#      - POSTGRES_USER=quarkus
#      - POSTGRES_PASSWORD=MyPassword
#      - QUARKUS_PROFILE=dev
#    expose:
#      - 8080
#      - 5005
#    ports:
#      - "8080:8080"
#      - "5005:5005"
#    depends_on:
#      - apint-postgres
#      - apint-redis
#    networks:
#      - apint

networks:
  apint:
    driver: bridge
